### ISSUE TITLE
what am I supposed to do here?

### ISSUE THREAD

**Issue by kyle-poretto** [learn-co-curriculum/rails-video-review-authentication#2]
this is a v poorly written lab. I've noticed the curriculum gets progressively worse as it goes on. Come on now

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestions.

Generally speaking, the videos are meant as material to augment the written curriculum and should be viewed as optional. After hearing feedback from students wanting more videos we have placed a few throughout the course. Because every student learns differently though, these videos are simply another way to deepen your understanding. If it doesn't work for you that's no problem. To better communicate this we will add a disclaimer explaining all of this to the lessons containing video resources. The written curriculum will independently cover all the required knowledge. Of course, we will continue to improve the videos and written material.

If, after reviewing the written curriculum, you still feel that there is a gap, feel free to reopen the issue.

As always, thanks for contributing! 💙
